#!/usr/local/bin/node 
'use strict'

var fs = require('fs')
var prompt = require('prompt')
var path = require('path');
var mkdirp = require('mkdirp');
var _ = require('underscore');
var partialRight = require('jsutils').partialRight;
var editor = require('editor');

function trim(str){
	return _.isString(str) ? str.trim() : str;
}

var trimEach = partialRight(_.map, trim);

prompt.message = 'Page';
prompt.start();

prompt.get(['author','title', 'folder', 'summary', 'tags'], function(err, data){
	data.date = new Date();

	if(data.tags)
		data.tags = trimEach(data.tags.split(','));
	
	var dir = path.join(__dirname, 'pages', data.folder);
	var file = path.join(dir,  data.title.replace(/\s/g,'-').toLowerCase());

	mkdirp(dir, function (){
		fs.writeFile(file + '.json', JSON.stringify(data, null, '\t'), function(err){
			var mkd = file + '.mkd';
			fs.writeFile(mkd, '');
			editor(mkd);
		});
	});
});

