#!/usr/local/bin/node 
var fs = require('fs')
var prompt = require('prompt')
var path = require('path');

prompt.message = 'Page';
prompt.start();

var file;
prompt.get(['author','title', 'folder', 'summary', 'tags'], function(err, data){
	data.date = new Date();

	if(data.tags && !Array.isArray(data.tags))
		data.tags = [data.tags];

	file = path.join(__dirname, 'pages', data.folder, data.title.replace(/\s/g,'-').toLowerCase());

	fs.writeFile(file + '.json', JSON.stringify(data, null, '\t'), function(err){
		var mkd = file + '.mkd';
		fs.writeFile(mkd, '');
	});
});

